// GENERATED by scripts/fetch-banners.mjs on 2026-09-12. Do not edit by hand.
// One committed Pexels photo per inner page, under public/banners/<slug>-{1600,900}.webp.
// The Pexels licence needs no attribution; the photographer is recorded here as a courtesy.

export type BannerSlug = 'work' | 'lumaiq' | 'the-ninth-room' | 'mdcb-study' | 'about' | 'resume' | 'not-found'

export interface Banner {
  id: number
  photographer: string
  photographerUrl: string
  url: string
  alt: string
  avgColor: string
}

export const BANNERS: Record<BannerSlug, Banner> = {
  "work": {
    "id": 25461703,
    "photographer": "Greece-China  News",
    "photographerUrl": "https://www.pexels.com/@greece-china-news-81838757",
    "url": "https://www.pexels.com/photo/lockers-in-a-hallway-25461703/",
    "alt": "A perspective view of a long hallway featuring rows of metal lockers and wooden flooring.",
    "avgColor": "#635A51"
  },
  "lumaiq": {
    "id": 37661099,
    "photographer": "Jan van der Wolf",
    "photographerUrl": "https://www.pexels.com/@jan-van-der-wolf-11680885",
    "url": "https://www.pexels.com/photo/industrial-garage-doors-under-clear-blue-sky-37661099/",
    "alt": "Image of industrial garage doors with corrugated metal under a clear blue sky, featuring a minimalist architectural style.",
    "avgColor": "#7D8C9F"
  },
  "the-ninth-room": {
    "id": 32774292,
    "photographer": "Fuka jaz",
    "photographerUrl": "https://www.pexels.com/@fukajaz",
    "url": "https://www.pexels.com/photo/professional-video-editing-software-on-screen-32774292/",
    "alt": "Close-up view of professional video editing software displaying colorful waveforms.",
    "avgColor": "#141311"
  },
  "mdcb-study": {
    "id": 8921700,
    "photographer": "Bikram Bezbaruah",
    "photographerUrl": "https://www.pexels.com/@bikibez",
    "url": "https://www.pexels.com/photo/a-woman-with-eyeglasses-writing-on-white-paper-under-a-light-8921700/",
    "alt": "A student intensely studying under a desk lamp, surrounded by books, in a black and white setting.",
    "avgColor": "#1F1F1F"
  },
  "about": {
    "id": 19334920,
    "photographer": "Benny Hassum",
    "photographerUrl": "https://www.pexels.com/@benny-hassum-162810415",
    "url": "https://www.pexels.com/photo/golf-course-under-a-dramatic-sky-at-sunset-19334920/",
    "alt": "Dramatic sunset sky over a lush green golf course, perfect for relaxation and leisure.",
    "avgColor": "#655A44"
  },
  "resume": {
    "id": 10769626,
    "photographer": "kingsley li",
    "photographerUrl": "https://www.pexels.com/@kingsley-li-159057939",
    "url": "https://www.pexels.com/photo/low-angle-shot-of-tall-buildings-in-the-city-during-night-time-10769626/",
    "alt": "Nighttime view of Houston's modern skyline featuring illuminated skyscrapers against a dark sky.",
    "avgColor": "#4F595B"
  },
  "not-found": {
    "id": 16071107,
    "photographer": "Julio  Agreda",
    "photographerUrl": "https://www.pexels.com/@julio-agreda-5105",
    "url": "https://www.pexels.com/photo/an-empty-asphalt-road-in-city-at-night-16071107/",
    "alt": "Foggy road illuminated by streetlights at night, capturing an eerie urban atmosphere.",
    "avgColor": "#101519"
  }
}

export const bannerSrc = (slug: BannerSlug, width: 900 | 1600) => `/banners/${slug}-${width}.webp`
