// Chooses and commits one banner photo per inner page from Pexels.
//
//   node --env-file=tmp/.env.pexels scripts/fetch-banners.mjs --candidates      list the top results per query as small JPEGs under tmp/banners/
//   node --env-file=tmp/.env.pexels scripts/fetch-banners.mjs                   download the chosen ids, write the WebPs and src/lib/banners.ts
//
// PEXELS_KEY is a free key from pexels.com/api in the local file above and
// nowhere else; it was removed from the Vercel project on 2026-09-16 because
// nothing at build or run time reads it. The photos are committed
// as WebP (1600 and 900 wide, under the same budgets as the home posters) so
// the site never calls Pexels at build or run time, the contrast test in
// src/lib/home.assets.test.ts can measure each frame under the band's scrim,
// and a Pexels outage cannot break a deploy. The Pexels licence needs no
// attribution; the photographer and page are recorded in banners.ts anyway.

import { mkdirSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import sharp from 'sharp'

const ROOT = new URL('../', import.meta.url).pathname
const OUT = join(ROOT, 'public/banners')
const TMP = join(ROOT, 'tmp/banners')
mkdirSync(OUT, { recursive: true })
mkdirSync(TMP, { recursive: true })
const KEY = process.env.PEXELS_KEY
if (!KEY) { console.error('PEXELS_KEY is not set: put a key from pexels.com/api in tmp/.env.pexels and run with --env-file'); process.exit(1) }
const CANDIDATES = process.argv.includes('--candidates')
const CAPS = { 1600: 160 * 1024, 900: 70 * 1024 }

/** One entry per inner page. `query` finds candidates; `id` is the chosen photo. */
export const BANNERS = {
  work:               { query: 'self storage units corridor', id: 25461703 },      // a corridor of grey unit doors
  lumaiq:             { query: 'storage unit roll up doors row', id: 37661099 },   // a row of roll-up doors on a white building
  'the-ninth-room':   { query: 'video editing timeline dark', id: 32774292 },      // DaVinci Resolve's colour page on a laptop
  'mdcb-study':       { query: 'study desk notes lamp night', id: 8921700 },       // studying under a lamp among books, black and white
  about:              { query: 'golf driving range dusk', id: 19334920 },          // a golf course at dusk, no people
  resume:             { query: 'houston skyline night', id: 10769626 },            // downtown Houston at night
  'not-found':        { query: 'empty road night fog', id: 16071107 },             // a lit road into fog
}

const api = async (path) => {
  const r = await fetch(`https://api.pexels.com/v1/${path}`, { headers: { Authorization: KEY } })
  if (!r.ok) throw new Error(`pexels ${path} ${r.status}`)
  return r.json()
}

async function candidates(slug, query) {
  const j = await api(`search?query=${encodeURIComponent(query)}&orientation=landscape&size=large&per_page=8`)
  const rows = []
  for (const p of j.photos) {
    const buf = Buffer.from(await (await fetch(p.src.medium)).arrayBuffer())
    const file = join(TMP, `${slug}-${p.id}.jpg`)
    writeFileSync(file, buf)
    rows.push(`${slug}  id ${p.id}  ${p.width}x${p.height}  avg ${p.avg_color}  by ${p.photographer}  ${p.url}`)
  }
  return rows
}

async function commit(slug, id) {
  const p = await api(`photos/${id}`)
  const src = Buffer.from(await (await fetch(p.src.original)).arrayBuffer())
  const out = {}
  for (const width of [1600, 900]) {
    const file = join(OUT, `${slug}-${width}.webp`)
    for (const quality of [78, 72, 66, 60, 54, 48]) {
      await sharp(src).resize(width, Math.round(width * 9 / 16), { fit: 'cover', position: 'attention' }).webp({ quality }).toFile(file)
      if (statSync(file).size <= CAPS[width]) { out[width] = `${(statSync(file).size / 1024).toFixed(0)} KB q${quality}`; break }
    }
  }
  console.log(`${slug}  ${p.id}  ${out[1600]}  ${out[900]}  by ${p.photographer}`)
  return { id: p.id, photographer: p.photographer, photographerUrl: p.photographer_url, url: p.url, alt: p.alt ?? '', avgColor: p.avg_color }
}

if (CANDIDATES) {
  for (const [slug, b] of Object.entries(BANNERS)) for (const row of await candidates(slug, b.query)) console.log(row)
} else {
  const record = {}
  for (const [slug, b] of Object.entries(BANNERS)) {
    if (!b.id) { console.error(`${slug}: no id chosen yet (run --candidates and set it)`); continue }
    record[slug] = await commit(slug, b.id)
  }
  const ts = `// GENERATED by scripts/fetch-banners.mjs on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
// One committed Pexels photo per inner page, under public/banners/<slug>-{1600,900}.webp.
// The Pexels licence needs no attribution; the photographer is recorded here as a courtesy.

export type BannerSlug = ${Object.keys(record).map((k) => `'${k}'`).join(' | ')}

export interface Banner {
  id: number
  photographer: string
  photographerUrl: string
  url: string
  alt: string
  avgColor: string
}

export const BANNERS: Record<BannerSlug, Banner> = ${JSON.stringify(record, null, 2)}

export const bannerSrc = (slug: BannerSlug, width: 900 | 1600) => \`/banners/\${slug}-\${width}.webp\`
`
  writeFileSync(join(ROOT, 'src/lib/banners.ts'), ts)
  console.log('wrote src/lib/banners.ts')
}
